package xyz.codegeek.outbreakvisualizer.helpers

val countryFlag = mapOf<String, String>(
    "Andorra" to "ad",
    "United Arab Emirates" to "ae",
    "US" to "us",
    "Afghanistan" to "af",
    "Albania" to "al",
    "Armenia" to "am",
    "Canada" to "ca",
    "United Kingdom" to "gb",
    "China" to "cn",
    "Netherlands" to "nl",
    "Australia" to "au",
    "Angola" to "ao",
    "Argentina" to "ar",
    "American Samoa" to "as",
    "Austria" to "at",
    "Aruba" to "aw",
    "Azerbaijan" to "az",
    "Bosnia and Herzegovina" to "ba",
    "Barbados" to "bb",
    "Bangladesh" to "bd",
    "Belgium" to "be",
    "Burkina Faso" to "bf",
    "Bulgaria" to "bg",
    "Bahrain" to "bh",
    "Burundi" to "bi",
    "Benin" to "bi",
    "Bolivia" to "bo",
    "Brazil" to "br",
    "Bahamas" to "bs",
    "Bhutan" to "bt",
    "Bouvel Island" to "bv",
    "Botswana" to "bw",
    "Belarus" to "by",
    "Belize" to "bz",
    "Congo (Kinshasa)" to "cd",
    "Congo (Brazzaville)" to "cg",
    "Central African Republic" to "cf",
    "Switzerland" to "ch",
    "Cote d'Ivoire" to "ci",
    "Cook Islands" to "ck",
    "Chile" to "cl",
    "Cameroon" to "cm",
    "Colombia" to "co",
    "Costa Rica" to "cr",
    "Cuba" to "cu",
    "Cabo Verde" to "cv",
    "Curacao" to "cw",
    "Christmas Island" to "cx",
    "Cyprus" to "cy",
    "Czechia" to "cz",
    "Germany" to "de",
    "Djibouti" to "dj",
    "Dominica" to "dm",
    "Dominican Republic" to "do",
    "Algeria" to "dz",
    "Ecuador" to "ec",
    "Estonia" to "ee",
    "Egypt" to "eg",
    "Western Sahara" to "eh",
    "Eritrea" to "er",
    "Spain" to "es",
    "Ethiopia" to "et",
    "Finland" to "fi",
    "Fiji" to "fj",
    "Gabon" to "ga",
    "Grenada" to "gd",
    "Georgia" to "ge",
    "French Guiana" to "gf",
    "Guernsey" to "gg",
    "Ghana" to "gh",
    "Gibraltar" to "gi",
    "Greenland" to "gl",
    "Gambia" to "gm",
    "Guinea" to "gn",
    "Guadeloupe" to "gp",
    "Equatorial Guinea" to "gq",
    "Greece" to "gr",
    "Guatemala" to "gt",
    "Guam" to "gu",
    "Guinea-Bissau" to "gw",
    "Guyana" to "gy",
    "Hong kong" to "hk",
    "Honduras" to "hn",
    "Croatia" to "hr",
    "Haiti" to "ht",
    "Hungary" to "hu",
    "Indonesia" to "id",
    "Ireland" to "ie",
    "Israel" to "il",
    "Isle of Man" to "im",
    "India" to "in",
    "Iraq" to "iq",
    "Iran" to "ir",
    "Iceland" to "is",
    "Italy" to "it",
    "Jersey" to "je",
    "Jamaica" to "jm",
    "Jordan" to "jo",
    "Japan" to "jp",
    "Kenya" to "ke",
    "Kyrgyzstan" to "kg",
    "Cambodia" to "kh",
    "Kiribati" to "ki",
    "Comoros" to "km",
    "Saint Kitts and Nevis" to "kn",
    "Korea" to "kr",
    "Kuwait" to "kw",
    "Cayman Islands" to "ky",
    "Kazakhstan" to "kz",
    "Lebanon" to "lb",
    "Saint Lucia" to "lc",
    "Liechtenstein" to "li",
    "Sri Lanka" to "lk",
    "Liberia" to "lr",
    "Lesotho" to "ls",
    "Lithuania" to "lt",
    "Luxembourg" to "lu",
    "Latvia" to "lv",
    "Libya" to "ly",
    "Morocco" to "ma",
    "Monaco" to "mc",
    "Moldova" to "md",
    "Montenegro" to "me",
    "Saint Martin" to "mf",
    "Madagascar" to "mg",
    "Marshall Islands" to "mh",
    "Macedonia" to "mk",
    "Mali" to "ml",
    "Myanmar" to "mm",
    "Mongolia" to "mn",
    "Macao" to "mo",
    "Martinique" to "mq",
    "Mauritania" to "mr",
    "Montserrat" to "ms",
    "Malta" to "mt",
    "Mauritius" to "mu",
    "Maldives" to "mv",
    "Malawi" to "mw",
    "Mexico" to "mx",
    "Malaysia" to "my",
    "Mozambique" to "mz",
    "Namibia" to "na",
    "New Caledonia" to "nc",
    "Niger" to "ne",
    "Norfolk Island" to "nf",
    "Nigeria" to "ng",
    "Nicaragua" to "ni",
    "Norway" to "no",
    "Nepal" to "np",
    "Nauru" to "nr",
    "Niue" to "nu",
    "New Zealand" to "nz",
    "Oman" to "om",
    "Panama" to "pa",
    "Peru" to "pe",
    "French Polynesia" to "pf",
    "Papua New Guinea" to "pg",
    "Philippines" to "ph",
    "Pakistan" to "pk",
    "Poland" to "pl",
    "PitCairn" to "pn",
    "Saint Pierre And Miquelon" to "pm",
    "Portugal" to "pt",
    "Palau" to "pw",
    "Paraguay" to "py",
    "Qatar" to "qa",
    "Reunion" to "re",
    "Romania" to "ro",
    "Serbia" to "rs",
    "Russia" to "ru",
    "Rwanda" to "rw",
    "Saudi Arabia" to "sa",
    "Solomon Islands" to "sb",
    "Seychelles" to "sc",
    "Sudan" to "sd",
    "Sweden" to "se",
    "Singapore" to "sg",
    "Saint Helena" to "sh",
    "Slovenia" to "sl",
    "Slovakia" to "sk",
    "Sierra Leone" to "sl",
    "San Marino" to "sm",
    "Senegal" to "sn",
    "Somalia" to "so",
    "Suriname" to "sr",
    "South Sudan" to "ss",
    "Sao Tome and Principe" to "st",
    "El Salvador" to "sv",
    "Sint Maarten" to "sx",
    "Syria" to "sy",
    "Eswatini" to "sz",
    "Chad" to "td",
    "Togo" to "tg",
    "Thailand" to "th",
    "Tajikistan" to "tj",
    "Tokelad" to "tk",
    "Timor-Leste" to "tl",
    "Turkmenistan" to "tm",
    "Tunisia" to "tn",
    "Tonga" to "to",
    "Turkey" to "tr",
    "Trinidad and Tobago" to "tt",
    "Tuvalu" to "tv",
    "Taiwan*" to "tw",
    "Tanzania" to "tz",
    "Denmark" to "dk",
    "France" to "fr",
    "Uganda" to "ug",
    "Ukraine" to "ua",
    "Uruguay" to "uy",
    "Uzbekistan" to "uz",
    "Samoa" to "ws",
    "Yemen" to "ye",
    "Saint Vincent and the Grenadines" to "vc",
    "Venezuela" to "ve",
    "Vietnam" to "vn",
    "South Africa" to "za",
    "Zambia" to "zm",
    "Zimbabwe" to "zw",
    "Holy See" to "va",
    "Kosovo" to "xk",
    "Laos" to "la",
    "Brunei" to "bn",
    "Antigua and Barbuda" to "ag",
    "North Macedonia" to "mk"

)